INSERT IGNORE INTO job_suggestion_dictionary (id, value, category, priority) VALUES
(UUID(), 'Software Engineer', 'ROLE', 1),
(UUID(), 'Backend Developer', 'ROLE', 1),
(UUID(), 'Frontend Developer', 'ROLE', 1),
(UUID(), 'Full Stack Developer', 'ROLE', 1),
(UUID(), 'Java Backend Engineer', 'ROLE', 1),
(UUID(), 'Python Developer', 'ROLE', 1),
(UUID(), 'React Developer', 'ROLE', 1),
(UUID(), 'Node.js Developer', 'ROLE', 1),
(UUID(), 'DevOps Engineer', 'ROLE', 1),
(UUID(), 'Cloud Engineer', 'ROLE', 1),
(UUID(), 'Data Analyst', 'ROLE', 1),
(UUID(), 'Data Scientist', 'ROLE', 1),
(UUID(), 'Machine Learning Engineer', 'ROLE', 1),
(UUID(), 'AI Engineer', 'ROLE', 1),
(UUID(), 'Automation Tester', 'ROLE', 1),
(UUID(), 'QA Engineer', 'ROLE', 1),
(UUID(), 'SDET', 'ROLE', 1),
(UUID(), 'Technical Lead', 'ROLE', 1),
(UUID(), 'Engineering Manager', 'ROLE', 1),
(UUID(), 'Solutions Architect', 'ROLE', 1),
(UUID(), 'Product Manager', 'ROLE', 1),
(UUID(), 'Associate Product Manager', 'ROLE', 1),
(UUID(), 'Business Analyst', 'ROLE', 1),
(UUID(), 'Project Manager', 'ROLE', 1),
(UUID(), 'Scrum Master', 'ROLE', 1),
(UUID(), 'UI UX Designer', 'ROLE', 1),
(UUID(), 'Graphic Designer', 'ROLE', 1),
(UUID(), 'Product Designer', 'ROLE', 1),
(UUID(), 'HR Executive', 'ROLE', 1),
(UUID(), 'HR Manager', 'ROLE', 1),
(UUID(), 'Recruiter', 'ROLE', 1),
(UUID(), 'Talent Acquisition Specialist', 'ROLE', 1),
(UUID(), 'Sales Executive', 'ROLE', 1),
(UUID(), 'Sales Manager', 'ROLE', 1),
(UUID(), 'Business Development Executive', 'ROLE', 1),
(UUID(), 'Account Manager', 'ROLE', 1),
(UUID(), 'Marketing Executive', 'ROLE', 1),
(UUID(), 'Digital Marketing Executive', 'ROLE', 1),
(UUID(), 'SEO Specialist', 'ROLE', 1),
(UUID(), 'Content Writer', 'ROLE', 1),
(UUID(), 'Social Media Manager', 'ROLE', 1),
(UUID(), 'Finance Analyst', 'ROLE', 1),
(UUID(), 'Accountant', 'ROLE', 1),
(UUID(), 'Financial Analyst', 'ROLE', 1),
(UUID(), 'Operations Manager', 'ROLE', 1),
(UUID(), 'Operations Executive', 'ROLE', 1),
(UUID(), 'Customer Support Executive', 'ROLE', 1),
(UUID(), 'Customer Success Manager', 'ROLE', 1),
(UUID(), 'Technical Support Engineer', 'ROLE', 1),
(UUID(), 'Support Specialist', 'ROLE', 1),
(UUID(), 'Network Engineer', 'ROLE', 1),
(UUID(), 'System Administrator', 'ROLE', 1),
(UUID(), 'Database Administrator', 'ROLE', 1),
(UUID(), 'Cyber Security Analyst', 'ROLE', 1),
(UUID(), 'Information Security Engineer', 'ROLE', 1),
(UUID(), 'Mobile App Developer', 'ROLE', 1),
(UUID(), 'Android Developer', 'ROLE', 1),
(UUID(), 'iOS Developer', 'ROLE', 1),
(UUID(), 'Flutter Developer', 'ROLE', 1),
(UUID(), 'Game Developer', 'ROLE', 1),
(UUID(), 'Blockchain Developer', 'ROLE', 1),
(UUID(), 'Embedded Engineer', 'ROLE', 1),
(UUID(), 'Site Reliability Engineer', 'ROLE', 1),
(UUID(), 'Cloud Consultant', 'ROLE', 1),
(UUID(), 'ERP Consultant', 'ROLE', 1),
(UUID(), 'SAP Consultant', 'ROLE', 1),
(UUID(), 'Operations Analyst', 'ROLE', 1),
(UUID(), 'Supply Chain Analyst', 'ROLE', 1),
(UUID(), 'Procurement Executive', 'ROLE', 1),
(UUID(), 'Logistics Coordinator', 'ROLE', 1),
(UUID(), 'Customer Relationship Manager', 'ROLE', 1),
(UUID(), 'Legal Associate', 'ROLE', 1),
(UUID(), 'Paralegal', 'ROLE', 1),
(UUID(), 'Research Analyst', 'ROLE', 1),
(UUID(), 'Consultant', 'ROLE', 1),
(UUID(), 'Strategy Analyst', 'ROLE', 1),
(UUID(), 'Investment Banking Analyst', 'ROLE', 1),
(UUID(), 'Operations Associate', 'ROLE', 1),
(UUID(), 'Executive Assistant', 'ROLE', 1),
(UUID(), 'Administrative Assistant', 'ROLE', 1),
(UUID(), 'Office Manager', 'ROLE', 1),
(UUID(), 'Hotel Manager', 'ROLE', 1),
(UUID(), 'Chef', 'ROLE', 1),
(UUID(), 'Event Manager', 'ROLE', 1),
(UUID(), 'Teacher', 'ROLE', 1),
(UUID(), 'Professor', 'ROLE', 1),
(UUID(), 'Instructional Designer', 'ROLE', 1),
(UUID(), 'Healthcare Administrator', 'ROLE', 1),
(UUID(), 'Pharmacist', 'ROLE', 1),
(UUID(), 'Nurse', 'ROLE', 1),
(UUID(), 'Doctor', 'ROLE', 1),
(UUID(), 'Physiotherapist', 'ROLE', 1),
(UUID(), 'Architect', 'ROLE', 1),
(UUID(), 'Civil Engineer', 'ROLE', 1),
(UUID(), 'Mechanical Engineer', 'ROLE', 1),
(UUID(), 'Electrical Engineer', 'ROLE', 1),
(UUID(), 'Chemical Engineer', 'ROLE', 1),
(UUID(), 'Industrial Engineer', 'ROLE', 1),
(UUID(), 'Interior Designer', 'ROLE', 1),
(UUID(), 'Fashion Designer', 'ROLE', 1),
(UUID(), 'Video Editor', 'ROLE', 1),
(UUID(), 'Animator', 'ROLE', 1),
(UUID(), 'Photographer', 'ROLE', 1),
(UUID(), 'Copywriter', 'ROLE', 1),
(UUID(), 'Journalist', 'ROLE', 1),
(UUID(), 'Public Relations Manager', 'ROLE', 1),
(UUID(), 'Community Manager', 'ROLE', 1),
(UUID(), 'Java', 'SKILL', 2),
(UUID(), 'Spring Boot', 'SKILL', 2),
(UUID(), 'Spring Security', 'SKILL', 2),
(UUID(), 'Microservices', 'SKILL', 2),
(UUID(), 'Kafka', 'SKILL', 2),
(UUID(), 'Docker', 'SKILL', 2),
(UUID(), 'Kubernetes', 'SKILL', 2),
(UUID(), 'AWS', 'SKILL', 2),
(UUID(), 'Azure', 'SKILL', 2),
(UUID(), 'GCP', 'SKILL', 2),
(UUID(), 'React', 'SKILL', 2),
(UUID(), 'Angular', 'SKILL', 2),
(UUID(), 'Vue.js', 'SKILL', 2),
(UUID(), 'JavaScript', 'SKILL', 2),
(UUID(), 'TypeScript', 'SKILL', 2),
(UUID(), 'Python', 'SKILL', 2),
(UUID(), 'C++', 'SKILL', 2),
(UUID(), 'SQL', 'SKILL', 2),
(UUID(), 'MySQL', 'SKILL', 2),
(UUID(), 'PostgreSQL', 'SKILL', 2),
(UUID(), 'MongoDB', 'SKILL', 2),
(UUID(), 'Redis', 'SKILL', 2),
(UUID(), 'HTML', 'SKILL', 2),
(UUID(), 'CSS', 'SKILL', 2),
(UUID(), 'Tailwind CSS', 'SKILL', 2),
(UUID(), 'Node.js', 'SKILL', 2),
(UUID(), 'Express.js', 'SKILL', 2),
(UUID(), 'Git', 'SKILL', 2),
(UUID(), 'Linux', 'SKILL', 2),
(UUID(), 'CI CD', 'SKILL', 2),
(UUID(), 'REST API', 'SKILL', 2),
(UUID(), 'GraphQL', 'SKILL', 2),
(UUID(), 'Machine Learning', 'SKILL', 2),
(UUID(), 'Deep Learning', 'SKILL', 2),
(UUID(), 'TensorFlow', 'SKILL', 2),
(UUID(), 'PyTorch', 'SKILL', 2),
(UUID(), 'Figma', 'SKILL', 2),
(UUID(), 'Adobe Photoshop', 'SKILL', 2),
(UUID(), 'Adobe Illustrator', 'SKILL', 2),
(UUID(), 'Canva', 'SKILL', 2),
(UUID(), 'Excel', 'SKILL', 2),
(UUID(), 'Power BI', 'SKILL', 2),
(UUID(), 'Tableau', 'SKILL', 2),
(UUID(), 'SEO', 'SKILL', 2),
(UUID(), 'Google Ads', 'SKILL', 2),
(UUID(), 'Meta Ads', 'SKILL', 2),
(UUID(), 'Performance Marketing', 'SKILL', 2),
(UUID(), 'Content Marketing', 'SKILL', 2),
(UUID(), 'Recruitment', 'SKILL', 2),
(UUID(), 'Payroll', 'SKILL', 2),
(UUID(), 'Lead Generation', 'SKILL', 2),
(UUID(), 'B2B Sales', 'SKILL', 2),
(UUID(), 'CRM', 'SKILL', 2),
(UUID(), 'Accounting', 'SKILL', 2),
(UUID(), 'Financial Modeling', 'SKILL', 2),
(UUID(), 'SAP', 'SKILL', 2),
(UUID(), 'Engineering', 'DOMAIN', 3),
(UUID(), 'Information Technology', 'DOMAIN', 3),
(UUID(), 'Product Management', 'DOMAIN', 3),
(UUID(), 'Human Resources', 'DOMAIN', 3),
(UUID(), 'Sales', 'DOMAIN', 3),
(UUID(), 'Marketing', 'DOMAIN', 3),
(UUID(), 'Finance', 'DOMAIN', 3),
(UUID(), 'Operations', 'DOMAIN', 3),
(UUID(), 'Customer Support', 'DOMAIN', 3),
(UUID(), 'Design', 'DOMAIN', 3),
(UUID(), 'Analytics', 'DOMAIN', 3),
(UUID(), 'Consulting', 'DOMAIN', 3);
